name: flutwear
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  wear: ^0.0.2

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
