name: flutwear
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  wear: ^0.0.2

  nima: ^1.0.0

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/hop.nima
    - assets/hop.png
